### ISSUE TITLE
NoClass found

### ISSUE THREAD

**Issue by michel5** [platelminto/java-bittrex#2]
Exception in thread "Timer-0" java.lang.NoClassDefFoundError: org/apache/http/nio/reactor/IOReactorException
	at com.mashape.unirest.http.HttpClientHelper.prepareRequest(HttpClientHelper.java:151)
	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:131)
	at com.mashape.unirest.request.BaseRequest.asJson(BaseRequest.java:68)

Caused by: java.lang.ClassNotFoundException: org.apache.http.nio.reactor.IOReactorException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 10 more

How can i fix this?

**Comment by platelminto** [comment]
What did you try to do before getting the error?

Also, have you got the dependencies listed in the [README](https://github.com/platelminto/java-bittrex/blob/master/README.md)?

**Comment by michel5** [comment]
I have remove line 27 - 29. 

    public void UpdateBalance (){
        System.out.println(apiKey);
        System.out.println(apiSecretKey);
        BittrexProtocall bittrexprotocall = new BittrexProtocall(apiKey, apiSecretKey);
        System.out.println(bittrexprotocall.getBalances());
    };

I have rename bittrex to BittrexProtocall.java. I add unirest-java-1.4.9.jar and gson-2.2.2.jar in Librarie.

**Comment by platelminto** [comment]
Try updating Gson to version 2.4 - also, how did you add the libraries? If you haven't used Maven, make sure you've imported all the required packages from both Gson & Unirest

**Comment by michel5** [comment]
I have add gson 2.4 and Maven (https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-jar-plugin/3.0.2). But i have still this problem. I have add the libraries in netbeans. Right click on libraries and add jar file and select the jar file then. Can you give your libraries?

**Comment by platelminto** [comment]
The Unirest dependency has now been removed - use Apache HttpClient with the new source code and it should now work.

**Comment by michel5** [comment]
Yeah! Good work! ty
